version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    networks:
      - backend-network 
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  express:
    build:
      context: .  # Path to your Dockerfile (current directory)
      dockerfile: "./Dockerfile"  # Explicitly specify the Dockerfile
    container_name: express
    networks:
      - backend-network
      - pdf_microservice_arch
    environment:
      - POSTGRES_USERNAME=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=job_store
      - EXPRESS_PORT=3000
      - EUREKA_APP_NAME=EXPRESSJS
      - EUREKA_HOST=job-service-eureka-1
      - EUREKA_PORT=8761
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
        
volumes:
  db:
    driver: local

networks:
  pdf_microservice_arch:
    external: true
  backend-network:
    external: false